--- 
env:
  browser: true

parser: 
  babel-eslint
  
extends: airbnb

rules:
  react/prop-types: 0
  react/sort-comp: 0
  react/state-in-constructor: 0
  react/destructuring-assignment: 0
  react/jsx-props-no-spreading: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0